import { Product } from '@/types'

export const newArrivals: Product[] = [
  {
    id: '1',
    name: 'Элегантная посуда с золотым ободком',
    description: 'Идеальна для особых случаев с ручной росписью золотыми акцентами на премиальном фарфоре',
    price: 299.99,
    oldPrice: 349.99,
    category: 'dinnerware',
    subcategory: 'Sets',
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 124,
    inStock: true,
    material: 'Тонкий фарфор с золотым ободком',
    dimensions: 'Тарелки диаметром 26,7 см, сервиз на 4 персоны',
    discount: 14,
    gradient: 'linear-gradient(135deg, #2a2a2a 0%, #3d3d3d 100%)',
  },
  {
    id: '2',
    name: 'Современное серое керамическое блюдо',
    description: 'Идеально для подачи закусок и десертов с современной матовой отделкой',
    price: 89.99,
    category: 'serveware',
    subcategory: 'Platters',
    isNewArrival: true,
    rating: 4.6,
    reviewCount: 89,
    inStock: true,
    material: 'Матовая керамика',
    dimensions: '40,6 x 30,5 см овальное',
    weight: '1,45 кг',
    gradient: 'linear-gradient(135deg, #e0e0e0 0%, #f5f5f5 100%)',
  },
  {
    id: '3',
    name: 'Изысканные позолоченные столовые приборы',
    description: 'Добавляют роскоши к любой трапезе благодаря стали 18/10 и золотому покрытию',
    price: 199.99,
    category: 'cutlery',
    subcategory: 'Flatware Sets',
    isNewArrival: true,
    rating: 4.9,
    reviewCount: 76,
    inStock: true,
    material: 'Нержавеющая сталь 18/10, позолота',
    dimensions: 'Набор 20 предметов, сервиз на 4 персоны',
    gradient: 'linear-gradient(135deg, #2a2a2a 0%, #3d3d3d 100%)',
  },
]

export const popularItems: Product[] = [
  {
    id: '4',
    name: 'Классические тарелки с золотым ободком',
    description: 'Вечная элегантность для любой сервировки с деликатным золотым ободком',
    price: 149.99,
    category: 'dinnerware',
    subcategory: 'Plates',
    isPopular: true,
    rating: 4.7,
    reviewCount: 203,
    inStock: true,
    material: 'Тонкий фарфор с золотым ободком',
    dimensions: 'Обеденные тарелки 26,7 см, набор из 6 штук',
    gradient: 'linear-gradient(135deg, #f0f0f0 0%, #fff 100%)',
  },
  {
    id: '5',
    name: 'Роскошные серые керамические миски',
    description: 'Изготовлены из лучшей керамики с применением ремесленных техник глазирования',
    price: 79.99,
    oldPrice: 99.99,
    category: 'dinnerware',
    subcategory: 'Bowls',
    isPopular: true,
    rating: 4.5,
    reviewCount: 156,
    inStock: true,
    material: 'Высокотемпературная керамика',
    dimensions: 'Диаметр 15,2 см, набор из 4 штук',
    discount: 20,
    gradient: 'linear-gradient(135deg, #2a2a2a 0%, #3d3d3d 100%)',
  },
  {
    id: '6',
    name: 'Дизайнерские позолоченные ложки',
    description: 'Улучшите впечатления от трапезы с премиальными позолоченными сервировочными ложками',
    price: 129.99,
    category: 'cutlery',
    subcategory: 'Serving Utensils',
    isPopular: true,
    rating: 4.8,
    reviewCount: 92,
    inStock: true,
    material: 'Нержавеющая сталь, позолота',
    dimensions: 'Сервировочные ложки 23 см, набор из 6 штук',
    gradient: 'linear-gradient(135deg, #2a2a2a 0%, #3d3d3d 100%)',
  },
]

// Additional products for more comprehensive catalog
export const additionalProducts: Product[] = [
  {
    id: '7',
    name: 'Коллекция бамбуковых сервировочных подносов',
    description: 'Экологичные бамбуковые сервировочные подносы с современным минималистским дизайном',
    price: 45.99,
    category: 'serveware',
    subcategory: 'Trays',
    rating: 4.4,
    reviewCount: 67,
    inStock: true,
    material: 'Экологичный бамбук',
    dimensions: '38 x 25,4 см прямоугольный',
    gradient: 'linear-gradient(135deg, #8B7355 0%, #A68B5B 100%)',
  },
  {
    id: '8',
    name: 'Кристальные бокалы для вина',
    description: 'Кристальные бокалы ручной работы для идеального впечатления от вина',
    price: 189.99,
    category: 'accessories',
    subcategory: 'Glassware',
    rating: 4.9,
    reviewCount: 134,
    inStock: false,
    material: 'Свинцовый кристалл',
    dimensions: 'Объём 250 мл, набор из 4 штук',
    gradient: 'linear-gradient(135deg, #E8E8E8 0%, #F5F5F5 100%)',
  },
  {
    id: '9',
    name: 'Ремесленный керамический обеденный сервиз',
    description: 'Ручной работы керамический обеденный сервиз с уникальными узорами глазури',
    price: 249.99,
    oldPrice: 299.99,
    category: 'dinnerware',
    subcategory: 'Sets',
    rating: 4.6,
    reviewCount: 88,
    inStock: true,
    material: 'Ремесленная керамика',
    dimensions: 'Набор 16 предметов, сервиз на 4 персоны',
    discount: 17,
    gradient: 'linear-gradient(135deg, #2a2a2a 0%, #3d3d3d 100%)',
  },
  {
    id: '10',
    name: 'Серебряные ножи для сыра',
    description: 'Элегантные ножи с серебряным покрытием для сыра для изысканных приёмов',
    price: 89.99,
    category: 'cutlery',
    subcategory: 'Specialty Items',
    rating: 4.7,
    reviewCount: 45,
    inStock: true,
    material: 'Посеребрённые',
    dimensions: 'Длина 15,2 см, набор из 4 штук',
    gradient: 'linear-gradient(135deg, #C0C0C0 0%, #E5E5E5 100%)',
  }
]

export const allProducts: Product[] = [...newArrivals, ...popularItems, ...additionalProducts]